sudo: false
language: node_js
matrix:
  include:
  - node_js: 5.9 # Latest stable
    env: REPORT_COVERAGE=true
  - node_js: 4.4 # LTS
    env: NPM_DEPLOY=true
  - node_js: 0.10 # Minimum supported
script:
- npm test
- npm run typecheck
after_success:
- '[[ "$REPORT_COVERAGE" = true ]] && cat coverage/lcov.info | ./node_modules/.bin/codecov'

cache:
  directories:
  - $HOME/.npm
